/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5c92285b797f3da694d2250982e79c06)
interface __BaseEnv_Env {
	UPSTREAM_AUTHORIZE_URL: "https://gulptwduchsjcsbndmua.supabase.co/auth/v1/oauth/authorize";
	UPSTREAM_TOKEN_URL: "https://gulptwduchsjcsbndmua.supabase.co/auth/v1/oauth/token";
	UPSTREAM_USERINFO_URL: "https://gulptwduchsjcsbndmua.supabase.co/auth/v1/oauth/userinfo";
	UPSTREAM_REDIRECT_URI: "https://sso.crove.com/callback";
	DOWNSTREAM_REDIRECT_URI: "https://post.crove.com/settings";
	ALLOWED_SCOPE: "openid profile email";
	OAUTH_STATE: DurableObjectNamespace<import("./src/index").OAuthStateStore>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "OAuthStateStore";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "UPSTREAM_AUTHORIZE_URL" | "UPSTREAM_TOKEN_URL" | "UPSTREAM_USERINFO_URL" | "UPSTREAM_REDIRECT_URI" | "DOWNSTREAM_REDIRECT_URI" | "ALLOWED_SCOPE">> {}
}
